# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''
# disqus-ID: x
# utterances-repo: x


assets:
  # logo: '/assets/site/logo.svg' 
  # badge: '/assets/site/logo.svg' 

menu:
# - {name: 'Tutorials', file: '/tutorials.html'}
- {name: 'Docs', file: 'https://github.com/dell-research-harvard/efficient-ocr'}

social:
# - {name: 'slack', icon: 'fab fa-slack-hash', link: ''}
- {name: 'Github', icon: 'fab fa-github', link: 'https://github.com/dell-research-harvard/efficient-ocr'}

# tutorials:
#   categories:
#     - {name: 'starter', title: 'Starter Example'}
#     - {name: 'usecase', title: 'Use Cases'}

footnote: >
  Created and maintained by EffOCR Developers. Built with [jekyll](https://jekyllrb.com/) and [bulma](http://bulma.io/).
